### PR TITLE
added a welcome text

### PR DESCRIPTION
**Pull request by pamood**

### CODE REVIEW

**Comment by srbmaury** [comment]
Can you please share a screenshot, of how it looks?

**Comment by pamood** [comment]
Sure ! here it is

**Comment by srbmaury** [comment]
I don't see any screenshot

**Comment by pamood** [comment]
[image: Screenshot (501).png]

**Comment by srbmaury** [comment]
Sir, instead of replying uselessly via email, can you please come to this page and reply properly?

**Comment by pamood** [comment]
you asked me to send a screenshot. That's why I replied.

sorry. u can ignore my pull-request

**Comment by srbmaury** [comment]
I can only see this text [image: Screenshot (501).png] but no image.

**Comment by pamood** [comment]
dude check the attachments.

**Pull request closed without merging**
