### PR TITLE
added better error msg for name field

### PR DESCRIPTION
**Pull request by love-sonkar**
[feat] : #35 added a nice error msg when user presses next button without entering name

# screenshot 
eeeee

### CODE REVIEW

**Comment by srbmaury** [comment]
The font looks a bit larger than what we see usually and is shifted a bit toward the right unnecessarily. Can you please take reference from some websites to modify this accordingly?

**Comment by love-sonkar** [comment]
hey @srbmaury i have added a toast notification and some animation
you can check

# screenshot 
new error msg container

# video 
https://github.com/srbmaury/quiz1/assets/82786865/d52aba93-2820-4be6-828f-f52dd18cae5b

**Comment by love-sonkar** [comment]
Thanks for merging this 🙏

**Comment by srbmaury** [comment]
> Thanks for merging this 🙏

Thanks for this contribution.

**Pull request merged**
