### PR TITLE
added background image and foldere

### PR DESCRIPTION
**Pull request by avimoti1234**

### CODE REVIEW

**Comment by srbmaury** [comment]
Can you please attach a working screenshot?

**Comment by avimoti1234** [comment]
take a look at the one that i have just commited

**Comment by srbmaury** [comment]
> take a look at the one that i have just commited

Please attach a screenshot. Also, I think there is no need to add unnecessary headers.

**Comment by avimoti1234** [comment]
i changed it,
now i have created a folder for images so whenever you would like to put some it will be easier and more arginized and i added logo for the site and additional headers so you can develop your site more profficiantly

**Comment by srbmaury** [comment]
Please attach a screenshot dude.

**Comment by avimoti1234** [comment]
sitere

**Comment by srbmaury** [comment]
Adding this is only making it worse
[image: image.png]
So I am closing this PR.

**Pull request closed without merging**
