### PR TITLE
fix submit button and prev button

### LINKED ISSUE #52: [Bug] : Submit button is broken when you finish quiz the submit btn is overflow
**Describe the bug**
when you finish the quiz the submit button in broken the text is overflow from button and the button size is also not good

**Expected behavior**
the text should be inside in the button and increase the size of button or fix any margin padding issue to fix this bug

**Screenshots**
btn

btnhover

### PR DESCRIPTION
**Pull request by love-sonkar**
# Title and Issue number 
fixes #52  
fixed some overflow issue and margin issue in button 

## Changes Made:
remove some repetative code and give some margins and padding to fix issue
for prev button i have added margin-left to 30px for better ui 

## Screenshot:
fixbtn

Close #<issue_no>
close #52 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by srbmaury** [comment]
Hey @love-sonkar, the buttons go out of the box on the mobile screen. Would you like to work on this?

**Comment by love-sonkar** [comment]
sure i can work on this, should i make Another issue then raise a PR or just Create another PR to fix the issue

**Comment by srbmaury** [comment]
create new one for that.

**Comment by love-sonkar** [comment]
okay thanks 👍 I'll start the work

**Pull request merged**
