### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Devansh-Singh-Parmar**
Please add all labels necessary, including, hacktoberfest-accepted, hacktoberfest

### CODE REVIEW

**Comment by Devansh-Singh-Parmar** [comment]
hacktoberfest too, please merge this

**Comment by srbmaury** [comment]
See If a repository has hacktoberfest label, or a PR has
hacktoberfest-accepted label both work (only one of them is needed). Please
stop writing useless comments.

**Comment by Devansh-Singh-Parmar** [comment]
Okkay, got it, merge it please then.

**Comment by srbmaury** [comment]
> Okkay, got it, merge it if you want. Thank you for the notice and apologies for being spammy.

I have asked a question above. Can you please answer it first?

**Comment by Devansh-Singh-Parmar** [comment]
Sorry I'm missing the question can you just rewrite that here, thank you so much in advance
cc @srbmaury

**Comment by srbmaury** [comment]
> - Change your directory to the project: `cd Quiz_App`
> - Install project dependencies: `npm install`

- Change your directory to the project: `cd Quiz_App`
- Install project dependencies: `npm install`
Are you sure about these two steps?

**Comment by Devansh-Singh-Parmar** [comment]
Sorry, I was into two Contributing.md issue, mismatched, now it's all okay please check.

**Comment by srbmaury** [comment]
> **[srbmaury](/srbmaury) ** started a review

Please check this

**Comment by srbmaury** [comment]
- That's enough, you can start the work from here.
remove this line and write: run ```cd quiz1```

**Comment by Devansh-Singh-Parmar** [comment]
Check it out

**Pull request merged**
