### PR TITLE
Changed background, button shapes, font size

### PR DESCRIPTION
**Pull request by aryanksanghvi**
I checked it once more, for me it is showing correctly. Can you please check once again?

### CODE REVIEW

**Comment by srbmaury** [comment]
Please make some meaningful contributions.

**Comment by aryanksanghvi** [comment]
I changed the background and font style and did center allignment

**Comment by srbmaury** [comment]
> I changed the background and font style and did center allignment

In files changed I can only see two empty lines removed.

**Comment by aryanksanghvi** [comment]
Yes because the files were already correct, they were running perfectly. I just had to make another pr

**Comment by srbmaury** [comment]
Can you please do the following things
1. Give some meaningful name to PR about what you are trying to update.
2. Provide a short description and screenshot of your change.

**Comment by aryanksanghvi** [comment]
image
image
image
image
image
image
image

**Comment by srbmaury** [comment]
Please double-check the branch you are pushing because I'm seeing only this much.
image

**Comment by aryanksanghvi** [comment]
Updated HTML, CSS, JS #26
https://github.com/srbmaury/quiz1/pull/26/files
i lost all my work, because you merged some other files. Kindly check this PR which you closed yesterday. You can find my work there

**Comment by srbmaury** [comment]
I believe the current UI looks much better than your proposed changes. Also, your PR had some conflicts with the master branch due to which merging resulted in some unexpected weird behavior. Also later someone modified HTML to look much better than this. You can check current code looks very different and the UI is also better so it will be unfeasible to merge your PR now. 

I hope you understand.

**Comment by aryanksanghvi** [comment]
Okay cool!

**Pull request closed without merging**
