### PR TITLE
Add a readme file #7

### PR DESCRIPTION
**Pull request by sagnik3788**
create a readme file for this repo @srbmaury issue #7

### CODE REVIEW

**Comment by srbmaury** [comment]
Please do only one commit. 9 commits are unnecessary.

**Comment by sagnik3788** [comment]
should i create a new pr for that ?

**Comment by srbmaury** [comment]
Yes, please!

**Comment by sagnik3788** [comment]
Due to current commits i cant squash them

**Comment by srbmaury** [comment]
Just copy your current contents of readme file. Fork again and make a fresh
new commit after deleting current forked repo.

**Comment by sagnik3788** [comment]
okay thanks

**Pull request closed without merging**
