### PR TITLE
make change in board size to contain all instruction

### PR DESCRIPTION
**Pull request by mohitahlawat2001**
image

this out of text from place is solved

this pull request is for hacktober please accept this!

### CODE REVIEW

**Comment by srbmaury** [comment]
have you checked for different screen sizes?

**Comment by mohitahlawat2001** [comment]
Yes

**Comment by mohitahlawat2001** [comment]
please add hacktoberfest and hacktoberfest-accept label 🙏🏻 
for hacktoberfest2023!

**Comment by srbmaury** [comment]
On the desktop screen, it looks like unnecessary extra space at the bottom. Can you please try adding a scrollbar instead to contain all instructions?

**Comment by mohitahlawat2001** [comment]
ok, let me try!

**Comment by srbmaury** [comment]
I've done that while correcting another issue.

**Pull request merged**
